services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    expose:
      - '${PORT}'
    env_file:
      - .env
    command: npm run test:unit